# Generated by Django 3.2.12 on 2022-02-10 13:29
# https://github.com/James1345/django-rest-knox/issues/220#issuecomment-779493269

from django.db import migrations


def convert_tokens(apps, schema_editor):
    AuthToken = apps.get_model("knox", "authtoken")
    Token = apps.get_model("apitokens", "token")

    for at in AuthToken.objects.all():
        child = Token(authtoken_ptr=at)
        child.save_base(raw=True)


class Migration(migrations.Migration):

    dependencies = [
        ('apitokens', '0001_initial'),
    ]

    operations = [migrations.RunPython(convert_tokens)]